Add GLM4.5V support (#863)
## Summary
<!--- This is a required section; please describe the main purpose of
this proposed code change. --->
This PR adds support for GLM4.1V (GLM-4 Vision) models to the Liger
Kernel https://github.com/linkedin/Liger-Kernel/issues/855
https://huggingface.co/zai-org/GLM-4.5
This model have been merged in
https://github.com/huggingface/transformers/pull/39805
<!---
## Details
This is an optional section; is there anything specific that reviewers
should be aware of?
--->

## Testing Done
<!--- This is a required section; please describe how this change was
tested. --->
Found that `python3 -m pytest test/convergence/bf16/test_mini_models.py
-k 'glm4v_moe' -rF`
has `AssertionError: [Loss]Number of mismatched elements: 14`
with 
<details>
  <summary>Test result</summary>

  ```
AssertionError: [Loss]Number of mismatched elements: 14
Mismatch at index (0, 5): tensor1[(0, 5)] = 8.733983993530273,
tensor2[(0, 5)] = 8.52511215209961
Mismatch at index (0, 8): tensor1[(0, 8)] = 7.2776618003845215,
tensor2[(0, 8)] = 7.524500846862793
Mismatch at index (0, 9): tensor1[(0, 9)] = 6.917590618133545,
tensor2[(0, 9)] = 7.175967216491699
Mismatch at index (0, 13): tensor1[(0, 13)] = 5.685216426849365,
tensor2[(0, 13)] = 5.427236557006836
Mismatch at index (0, 14): tensor1[(0, 14)] = 5.337466239929199,
tensor2[(0, 14)] = 5.049449443817139
  ... and 9 more mismatched elements.
```
</details>
<!-- 
Replace BLANK with your device type. For example, A100-80G-PCIe

Complete the following tasks before sending your PR, and replace `[ ]` with
`[x]` to indicate you have done them. 
-->

- Hardware Type: <BLANK>
- [x] run `make test` to ensure correctness
- [x] run `make checkstyle` to ensure code style
- [x] run `make test-convergence` to ensure convergence

---------

Co-authored-by: Shao Tang <tangshao28@gmail.com>
Co-authored-by: Steven Shimizu <shimizust@gmail.com>