fix: remove docstring imports in transformer patches (#712)
## Summary
<!--- This is a required section; please describe the main purpose of
this proposed code change. --->

Transformers did a refactor on docstrings to use autodocstring instead
on main. This would break any patches that import `_CONFIG_FOR_DOC` or
`*INPUTS_DOCSTRING`

https://github.com/huggingface/transformers/pull/33771

An error example:
```
ImportError: cannot import name '_CONFIG_FOR_DOC' from 'transformers.models.gemma.modeling_gemma' (/opt/hostedtoolcache/Python/3.11.12/x64/lib/python3.11/site-packages/transformers/models/gemma/modeling_gemma.py)
```

This PR removes any imports that would break it.

<!---
## Details
This is an optional section; is there anything specific that reviewers
should be aware of?
--->

## Testing Done
<!--- This is a required section; please describe how this change was
tested. --->

<!-- 
Replace BLANK with your device type. For example, A100-80G-PCIe

Complete the following tasks before sending your PR, and replace `[ ]`
with
`[x]` to indicate you have done them. 
-->

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [x] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence