annotate tl constexpr values (#497)
## Summary

Annotates tl.constexpr
## Details

When using torch.compile I get the error

```
   File "/tmp/torchinductor_root/5h/c5hmywscvfp53un2gehng5syunj2ibukwyyzqs3b3caewyhxjuff.py", line 89, in <module>                                                       
     _CASTING_MODE_LLAMA = constexpr[0]   
                           ^^^^^^^^^      
 NameError: name 'constexpr' is not defined                                                                                                                              
```

This was fixed upstream, but it's in 2.6.0, so not stable yet.
Converting this to an annotated expression resolves the issue.

## Testing Done
<!--- This is a required section; please describe how this change was
tested. --->

<!-- 
Replace BLANK with your device type. For example, A100-80G-PCIe

Complete the following tasks before sending your PR, and replace `[ ]`
with
`[x]` to indicate you have done them. 
-->

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [ ] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

---------

Co-authored-by: Byron Hsu <byronhsu1230@gmail.com>