[AMD] [CI] Added Dockerfile and AMD-CI test workflow (#430)
## Summary
<!--- This is a required section; please describe the main purpose of
this proposed code change. --->
This is a PR to suggests the use of Docker Images to run the Liger
Kernel CI on AMD Machine.

<!---
## Details
This is an optional section; is there anything specific that reviewers
should be aware of?
--->

## Details
When running the `docker run` you might need to run with `sudo`. In this
version, I have not included it. If you find problem using AMD GPU
within the docker container. Please add back the `sudo`. E.g.
```bash
sudo docker run \
   --network=host \
   --group-add=video \
   --ipc=host \
   --cap-add=SYS_PTRACE \
   --security-opt seccomp=unconfined \
   --device /dev/kfd \
   --device /dev/dri \
   liger-ci \
   /bin/bash -c "make test-convergence; make test"
```

## Additional Details

The `transformers` version has been pinned to `4.46.3` as there is a API
changes in the later version of `transformers`. E.g. I have tested with
`transformers==4.47.0` and the following error occured.
```bash
FAILED test/convergence/test_mini_models_multimodal.py::test_mini_model_multimodal[mini_qwen2_vl-32-0.0001-dtype0-1e-08-1e-05-0.005-1e-05-0.005-1e-05] - AttributeError: 'Qwen2VLConfig' object has no attribute 'video_token_id'. Did you mean: 'vision_token_id'?
FAILED test/convergence/test_mini_models_multimodal.py::test_mini_model_multimodal[mini_qwen2_vl-32-0.0001-dtype1-0.001-0.01-0.1-0.01-0.01-0.01] - AttributeError: 'Qwen2VLConfig' object has no attribute 'video_token_id'. Did you mean: 'vision_token_id'?
FAILED test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_qwen2_vl-32-0.0001-dtype6-1e-08-1e-05-0.005-1e-05-0.005-1e-05] - AttributeError: 'Qwen2VLConfig' object has no attribute 'image_token_id'. Did you mean: 'pad_token_id'?
FAILED test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_qwen2_vl-32-0.0001-dtype7-0.001-0.01-0.1-0.01-0.01-0.01] - AttributeError: 'Qwen2VLConfig' object has no attribute 'image_token_id'. Did you mean: 'pad_token_id'?
```

## Testing Done
<!--- This is a required section; please describe how this change was
tested. --->

<!-- 
Replace BLANK with your device type. For example, A100-80G-PCIe

Complete the following tasks before sending your PR, and replace `[ ]`
with
`[x]` to indicate you have done them. 
-->

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [ ] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

Co-authored-by: tjtanaa <tunjian.tan@embeddedllm.com>